<!DOCTYPE html>
<html>
<head>
    <title>Личный кабинет</title>
</head>
<body>

    <div class="headers">
        <h1 align="center">Личный кабинет</h1>
    </div>
    <div class="d-flex flex-wrap">
        <div class="exit">
            <h4 id="len"><a href="logout">ВЫЙТИ</a></h4>
        </div>
        <div class="exit">
            <h4 id="len"><a href="album">ТОВАРЫ</a></h4>
        </div>

    </div>
</body>
</html>